alias tf='terraform'
alias tfi='terraform init'
alias tfa='terraform apply --auto-approve'
alias tfd='terraform destroy --auto-approve'
alias tfp='terraform plan'
alias tfs='terraform show'
alias tff='terraform fmt'
alias tfv='terraform validate'
alias tfw='terraform workspace'
alias tfws='terraform workspace select'
alias tfwn='terraform workspace new'
alias tfwd='terraform workspace delete'
alias tfwl='terraform workspace list'
alias tfwsh='terraform workspace show'
alias tfwde='terraform workspace delete'
alias tfwse='terraform workspace select'

