{
 "title": "Synthetic Log Applications Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Synthetic App Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"synthetic_logs\"} |= ``"
    }
   ]
  },
  {
   "title": "404 Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"synthetic_logs\"} |= `404`"
    }
   ]
  },
  {
   "title": "200 - Success",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"synthetic_logs\"} |= `200`"
    }
   ]
  }
 ]
}